name: Deploy-Linode

on: workflow_dispatch

env:
  LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}

jobs:
  deploy-linode:
  name: "deploy a linode instance using Terraform"
  runs-on: ubuntu-latest
  steps:
    - name: install Terraform on runner
      run: apt upgrade && apt install terraform
    - name: check TF installation
      run: terraform version
#    - name: initialize TF
#      run: terraform init
#    - name: show TF plan
#      run: terraform plan
#    - name: deploy the TF
#      run: terraform plan -auto-approve
  
