name: Deploy-Linode

on: workflow_dispatch

env:
  LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}

jobs:
  deploy-linode:
    runs-on: ubuntu-latest
    steps:
      - name: install Terraform on runner
        # docs: https://www.linode.com/docs/guides/how-to-build-your-infrastructure-using-terraform-and-linode/#install-terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install terraform
      - name: check TF installation
        run: terraform version
      - name: initialize TF
        run: terraform init
      - name: show TF plan
        run: terraform plan
      - name: deploy the TF
        run: terraform plan -auto-approve
  
